// <auto-generated />
using System;
using BetterWeatherApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetterWeatherApi.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250828124356_extraDataAddedForDailyAndHourlyForecast")]
    partial class extraDataAddedForDailyAndHourlyForecast
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BetterWeatherApi.Data.Entities.DailyForecastEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HumidityAvg")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastRequest")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PressureSurfaceLevelAvg")
                        .HasColumnType("real");

                    b.Property<DateTime>("SunriseTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SunsetTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("TemperatureMax")
                        .HasColumnType("real");

                    b.Property<float>("TemperatureMin")
                        .HasColumnType("real");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeatherCodeMax")
                        .HasColumnType("int");

                    b.Property<int>("WindDirectionAvg")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyForecasts");
                });

            modelBuilder.Entity("BetterWeatherApi.Data.Entities.HourlyForecastEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastRequest")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PressureSurfaceLevel")
                        .HasColumnType("real");

                    b.Property<DateTime>("SunriseTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SunsetTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<float>("TemperatureApparent")
                        .HasColumnType("real");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("UvIndex")
                        .HasColumnType("int");

                    b.Property<int>("WeatherCode")
                        .HasColumnType("int");

                    b.Property<int>("WindDirection")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HourlyForecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
