public class WeatherCode
{
    public int Code { get; set; }
    public string Description { get; set; }
}

public static class WeatherCodes
{
    public static readonly List<WeatherCode> All = new List<WeatherCode>
    {
        new WeatherCode { Code = 0, Description = "Unknown" },
        new WeatherCode { Code = 1000, Description = "Clear, Sunny" },
        new WeatherCode { Code = 1100, Description = "Mostly Clear" },
        new WeatherCode { Code = 1101, Description = "Partly Cloudy" },
        new WeatherCode { Code = 1102, Description = "Mostly Cloudy" },
        new WeatherCode { Code = 1001, Description = "Cloudy" },
        new WeatherCode { Code = 1103, Description = "Partly Cloudy, Mostly Clear" },
        new WeatherCode { Code = 2100, Description = "Light Fog" },
        new WeatherCode { Code = 2101, Description = "Mostly Clear, Light Fog" },
        new WeatherCode { Code = 2102, Description = "Partly Cloudy, Light Fog" },
        new WeatherCode { Code = 2103, Description = "Mostly Cloudy, Light Fog" },
        new WeatherCode { Code = 2106, Description = "Mostly Clear, Fog" },
        new WeatherCode { Code = 2107, Description = "Partly Cloudy, Fog" },
        new WeatherCode { Code = 2108, Description = "Mostly Cloudy, Fog" },
        new WeatherCode { Code = 2000, Description = "Fog" },
        new WeatherCode { Code = 4204, Description = "Partly Cloudy, Drizzle" },
        new WeatherCode { Code = 4203, Description = "Mostly Clear, Drizzle" },
        new WeatherCode { Code = 4205, Description = "Mostly Cloudy, Drizzle" },
        new WeatherCode { Code = 4000, Description = "Drizzle" },
        new WeatherCode { Code = 4200, Description = "Light Rain" },
        new WeatherCode { Code = 4213, Description = "Mostly Clear, Light Rain" },
        new WeatherCode { Code = 4214, Description = "Partly Cloudy, Light Rain" },
        new WeatherCode { Code = 4215, Description = "Mostly Cloudy, Light Rain" },
        new WeatherCode { Code = 4209, Description = "Mostly Clear, Rain" },
        new WeatherCode { Code = 4208, Description = "Partly Cloudy, Rain" },
        new WeatherCode { Code = 4210, Description = "Mostly Cloudy, Rain" },
        new WeatherCode { Code = 4001, Description = "Rain" },
        new WeatherCode { Code = 4211, Description = "Mostly Clear, Heavy Rain" },
        new WeatherCode { Code = 4202, Description = "Partly Cloudy, Heavy Rain" },
        new WeatherCode { Code = 4212, Description = "Mostly Cloudy, Heavy Rain" },
        new WeatherCode { Code = 4201, Description = "Heavy Rain" },
        new WeatherCode { Code = 5115, Description = "Mostly Clear, Flurries" },
        new WeatherCode { Code = 5116, Description = "Partly Cloudy, Flurries" },
        new WeatherCode { Code = 5117, Description = "Mostly Cloudy, Flurries" },
        new WeatherCode { Code = 5001, Description = "Flurries" },
        new WeatherCode { Code = 5100, Description = "Light Snow" },
        new WeatherCode { Code = 5102, Description = "Mostly Clear, Light Snow" },
        new WeatherCode { Code = 5103, Description = "Partly Cloudy, Light Snow" },
        new WeatherCode { Code = 5104, Description = "Mostly Cloudy, Light Snow" },
        new WeatherCode { Code = 5122, Description = "Drizzle, Light Snow" },
        new WeatherCode { Code = 5105, Description = "Mostly Clear, Snow" },
        new WeatherCode { Code = 5106, Description = "Partly Cloudy, Snow" },
        new WeatherCode { Code = 5107, Description = "Mostly Cloudy, Snow" },
        new WeatherCode { Code = 5000, Description = "Snow" },
        new WeatherCode { Code = 5101, Description = "Heavy Snow" },
        new WeatherCode { Code = 5119, Description = "Mostly Clear, Heavy Snow" },
        new WeatherCode { Code = 5120, Description = "Partly Cloudy, Heavy Snow" },
        new WeatherCode { Code = 5121, Description = "Mostly Cloudy, Heavy Snow" },
        new WeatherCode { Code = 5110, Description = "Drizzle, Snow" },
        new WeatherCode { Code = 5108, Description = "Rain, Snow" },
        new WeatherCode { Code = 5114, Description = "Snow, Freezing Rain" },
        new WeatherCode { Code = 5112, Description = "Snow, Ice Pellets" },
        new WeatherCode { Code = 6000, Description = "Freezing Drizzle" },
        new WeatherCode { Code = 6003, Description = "Mostly Clear, Freezing Drizzle" },
        new WeatherCode { Code = 6002, Description = "Partly Cloudy, Freezing Drizzle" },
        new WeatherCode { Code = 6004, Description = "Mostly Cloudy, Freezing Drizzle" },
        new WeatherCode { Code = 6204, Description = "Drizzle, Freezing Drizzle" },
        new WeatherCode { Code = 6206, Description = "Light Rain, Freezing Drizzle" },
        new WeatherCode { Code = 6205, Description = "Mostly Clear, Light Freezing Rain" },
        new WeatherCode { Code = 6203, Description = "Partly Cloudy, Light Freezing Rain" },
        new WeatherCode { Code = 6209, Description = "Mostly Cloudy, Light Freezing Rain" },
        new WeatherCode { Code = 6200, Description = "Light Freezing Rain" },
        new WeatherCode { Code = 6213, Description = "Mostly Clear, Freezing Rain" },
        new WeatherCode { Code = 6214, Description = "Partly Cloudy, Freezing Rain" },
        new WeatherCode { Code = 6215, Description = "Mostly Cloudy, Freezing Rain" },
        new WeatherCode { Code = 6001, Description = "Freezing Rain" },
        new WeatherCode { Code = 6212, Description = "Drizzle, Freezing Rain" },
        new WeatherCode { Code = 6220, Description = "Light Rain, Freezing Rain" },
        new WeatherCode { Code = 6222, Description = "Rain, Freezing Rain" },
        new WeatherCode { Code = 6207, Description = "Mostly Clear, Heavy Freezing Rain" },
        new WeatherCode { Code = 6202, Description = "Partly Cloudy, Heavy Freezing Rain" },
        new WeatherCode { Code = 6208, Description = "Mostly Cloudy, Heavy Freezing Rain" },
        new WeatherCode { Code = 6201, Description = "Heavy Freezing Rain" },
        new WeatherCode { Code = 7110, Description = "Mostly Clear, Light Ice Pellets" },
        new WeatherCode { Code = 7111, Description = "Partly Cloudy, Light Ice Pellets" },
        new WeatherCode { Code = 7112, Description = "Mostly Cloudy, Light Ice Pellets" },
        new WeatherCode { Code = 7102, Description = "Light Ice Pellets" },
        new WeatherCode { Code = 7108, Description = "Mostly Clear, Ice Pellets" },
        new WeatherCode { Code = 7107, Description = "Partly Cloudy, Ice Pellets" },
        new WeatherCode { Code = 7109, Description = "Mostly Cloudy, Ice Pellets" },
        new WeatherCode { Code = 7000, Description = "Ice Pellets" },
        new WeatherCode { Code = 7105, Description = "Drizzle, Ice Pellets" },
        new WeatherCode { Code = 7106, Description = "Freezing Rain, Ice Pellets" },
        new WeatherCode { Code = 7115, Description = "Light Rain, Ice Pellets" },
        new WeatherCode { Code = 7117, Description = "Rain, Ice Pellets" },
        new WeatherCode { Code = 7103, Description = "Freezing Rain, Heavy Ice Pellets" },
        new WeatherCode { Code = 7113, Description = "Mostly Clear, Heavy Ice Pellets" },
        new WeatherCode { Code = 7114, Description = "Partly Cloudy, Heavy Ice Pellets" },
        new WeatherCode { Code = 7116, Description = "Mostly Cloudy, Heavy Ice Pellets" },
        new WeatherCode { Code = 7101, Description = "Heavy Ice Pellets" },
        new WeatherCode { Code = 8001, Description = "Mostly Clear, Thunderstorm" },
        new WeatherCode { Code = 8003, Description = "Partly Cloudy, Thunderstorm" },
        new WeatherCode { Code = 8002, Description = "Mostly Cloudy, Thunderstorm" },
        new WeatherCode { Code = 8000, Description = "Thunderstorm" },
    };
}